### ISSUE TITLE
Exception: Service invoked too many times for one day: urlfetch.

### ISSUE THREAD

**Issue by benniefolyfe** [bumbleshoot/automate-habitica#10]
**What is the bug?**

Exception: Service invoked too many times for one day: urlfetch.
     at fetch (global:576:32)
     at getUser (global:720:14)
     at pauseResumeDamage (automations/pauseResumeDamage:23:17)
     at processQueue (global:341:13)
     at doPost (global:88:5)
     at __GS_INTERNAL_top_function_call__.gs:1:8

Exception: Service invoked too many times for one day: urlfetch.
     at fetch (global:576:32)
     at getUser (global:720:14)
     at getTotalStat (global:664:13)
     at castValorousPresence (automations/castWarriorSkills:33:17)
     at useExcessMana (global:530:5)
     at processQueue (global:388:11)
     at onTrigger (global:27:5)
     at __GS_INTERNAL_top_function_call__.gs:1:8

**Additional context**

This is happening on only one of my email addresses that has Automate Habitica running. I have this running on 8 accounts, but my main account is having the most trouble. I have two other scripts running on really sparse triggers (once per day, and 3x per day), also on all 8 accounts. 

**How often does this happen?**

On my main account, this happens daily, and when it starts, it will send me anywhere from 50-150 emails over the course of the day, with several varitations on the above error message, one apparently for each function trying to run.

**Script version**

v0.29.15

**Script settings**

const AUTO_CRON = true; // true or false

const AUTO_ACCEPT_QUEST_INVITES = true;

const FORCE_START_QUESTS = false; // party leaders only
const FORCE_START_QUESTS_AFTER_HOURS = 1; // eg. if set to 1, quests will force start after 1h
const NOTIFY_MEMBERS_EXCLUDED_FROM_QUEST = false;

const AUTO_INVITE_GOLD_QUESTS = false;
const AUTO_INVITE_UNLOCKABLE_QUESTS = false;
const AUTO_INVITE_PET_QUESTS = false;
const AUTO_INVITE_HOURGLASS_QUESTS = false;
const PM_WHEN_OUT_OF_QUEST_SCROLLS = false;

const NOTIFY_ON_QUEST_END = false;

const AUTO_CAST_SKILLS = true;

const AUTO_PAUSE_RESUME_DAMAGE = true;
const MAX_PLAYER_DAMAGE = 20;
const MAX_PARTY_DAMAGE = 5;

const AUTO_ALLOCATE_STAT_POINTS = false;
const STAT_TO_ALLOCATE = "str"; // str, int, con, per

const AUTO_PURCHASE_GEMS = true; // subscribers only

const AUTO_PURCHASE_ARMOIRES = true;
const RESERVE_GOLD = 1000;

const AUTO_SELL_EGGS = false;
const RESERVE_EGGS = 999;

const AUTO_SELL_HATCHING_POTIONS = false;
const RESERVE_HATCHING_POTIONS = 999;

const AUTO_SELL_FOOD = false;
const RESERVE_FOOD = 999;

const AUTO_HATCH_FEED_PETS = false;
const ONLY_USE_DROP_FOOD = true;

const HIDE_PARTY_NOTIFICATIONS = false;
const HIDE_ALL_GUILD_NOTIFICATIONS = false;
const HIDE_NOTIFICATIONS_FROM_SPECIFIC_GUILDS = [ // only used if HIDE_ALL_GUILD_NOTIFICATIONS is false
  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", // enter a guild ID between the quotes to hide notifications from that guild
  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" // repeat for as many guilds as you want
]

**Comment by benniefolyfe** [comment]
Oh goodness, don’t judge me. On all 8 accounts I’m running:


  1.  Set Self Buffs, a single script to set the baseline buffs at 1-2am every day.
  2.  A script I call “Auto Use Tasks”, which every 8 hours uses a single skill 15 times to gain mana for buffs and deal damage.

I can copy you the code for one or both if you’d like to see it.

I rely on Automate Habitica to cast buffs and accept quests.

I’m also running your/Snefferdy’s Quest Queue on one account, and I don’t think I’ve run into this issue on that account yet.

I don’t think you need an explanation, but so you understand, I basically stopped using Habitica as a task management app when the whole social system imploded, including my party. I’m now basically using it to keep in touch with people and share knowledge with new parties and users. We’ll call it “shadow socialiting.”

From: Bumbleshoot ***@***.***>
one day: urlfetch. (Issue #10)

Hi @benniefolyfe<https://github.com/benniefolyfe>! Thanks for the detailed bug report! What other Google Scripts are you running on the Google account with the script that is emailing you the errors?

**Comment by bumbleshoot** [comment]
@benniefolyfe No judgement. :) So the Google account that is emailing you the errors is running:

1. Automate Habitica
2. Self Set Buffs
3. Auto Use Tasks

and no other Google scripts, for Habitica or anything else? If I got that right, can I please see the code for Auto Use Tasks?

FYI - your Google account is exceeding the 20,000 per day URL Fetch call limit [here](https://developers.google.com/apps-script/guides/services/quotas), so all your Google scripts combined on that account are calling URL Fetch more than 20,000 times in a day. Automate Habitica won't exceed this limit on its own, and it leaves some room for other scripts to run URL Fetch calls too, but maybe one of your other scripts is calling `UrlFetchApp.fetch()` a bunch too?

**Comment by benniefolyfe** [comment]
Today my main account hit the error at 1:28 AM PDT. It seems there is some carryover, like my account is clocked for a day or a few days on any day where I reach the limit, and therefore the next day it isn’t reset. Although, I am thinking of it in terms of my own time zone, not knowing in what time zone Habitica is officially set.

Here’s the code for Auto Use Tasks.

const habId = ""; //
const habToken = "";
const taskId = "";

// set number of times to increase score and milliseconds to sleep between increases (2500 = 2.5 seconds). Sleep time keeps Habitica servers from rejecting API calls from the user. 2500 is the lowest allowed.

const n = 15;
const sleepTime = 2500

function increaseTaskScore() {
  // set API endpoint
  var url = https://habitica.com/api/v3/tasks/ + taskId + "/score/up";

  // set API headers
  var headers = {
    "x-api-user": habId,
    "x-api-key": habToken,
  };

  // set API options
  var options = {
    "method": "post",
    "headers": headers,
  };

  // increase task score n times
  for (var i = 0; i < n; i++) {
    var response = UrlFetchApp.fetch(url, options);
    var result = JSON.parse(response.getContentText());
    Logger.log("Task score increased by " + result.data.delta);
    Utilities.sleep(sleepTime);
  }
}


From: Bumbleshoot ***@***.***>
one day: urlfetch. (Issue #10)

@benniefolyfe<https://github.com/benniefolyfe> No judgement. :) So the Google account that is emailing you the errors is running:

  1.  Automate Habitica
  2.  Self Set Buffs
  3.  Auto Use Tasks

and no other Google scripts, for Habitica or anything else? If I got that right, can I please see the code for Auto Use Tasks?

FYI - your Google account is exceeding the 20,000 per day URL Fetch call limit here<https://developers.google.com/apps-script/guides/services/quotas>, so all your Google scripts combined on that account are calling URL Fetch more than 20,000 times in a day. Automate Habitica won't exceed this limit on its own, and it leaves some room for other scripts to run URL Fetch calls too, but maybe one of your other scripts is calling UrlFetchApp.fetch() a bunch too?

**Comment by bumbleshoot** [comment]
@benniefolyfe I don’t see anything here that should cause the error (which is not in your time zone btw, the reset happens on Google’s servers so it’s based on where the servers are). Are you absolutely certain Auto Use Tasks is only running every 8h? (You can check the trigger by logging into the Google account that got the error, opening the script, and clicking on Triggers in the main menu on the left.) Are you absolutely certain only those 3 scripts (Automate Habitica, Self Set Buffs, Auto Use Tasks) are running on the Google account you got the error email from? (You can see a list of your scripts by logging into that Google account and going to [scripts.google.com](https://script.google.com/home).) If yes to both of these questions, can you please grant me Editor access to your copy of Automate Habitica (using the email address I sent you privately) so I can take a look? Thanks!

**Comment by benniefolyfe** [comment]
Unfortunately I don’t have the same setup anymore. I reworked my whole system of scripts to take Automate Habitica out of it so I could stay in my party. I’d like to reinstall it if I can get over this hurdle we’re discussing. I also deleted the scripts because [complicated unnecessary explanation], so I don’t think I can even see the run history.

Short answer, yes, I’m confident on the run times and number of times for those other two scripts because I designed them and I didn’t include anything except the single simple calls, so the only times they run are the triggers I set.

From: Bumbleshoot ***@***.***>
Date: Thursday, March 30, 2023 at 10:47 AM
To: bumbleshoot/automate-habitica ***@***.***>
Cc: Bennie, the Shepherd ***@***.***>, Mention ***@***.***>
Subject: Re: [bumbleshoot/automate-habitica] Exception: Service invoked too many times for one day: urlfetch. (Issue #10)

@benniefolyfe<https://github.com/benniefolyfe> I don’t see anything here that should cause the error (which is not in your time zone btw, the reset happens on Google’s servers so it’s based on where the servers are). Are you absolutely certain Auto Use Tasks is only running every 8h? (You can check the trigger by logging into the Google account that got the error, opening the script, and clicking on Triggers in the main menu on the left.) Are you absolutely certain only those 3 scripts (Automate Habitica, Self Set Buffs, Auto Use Tasks) are running on the Google account you got the error email from? (You can see a list of your scripts by logging into that Google account and going to scripts.google.com<https://script.google.com/home>.) If yes to both of these questions, can you please grant me Editor access to your copy of Automate Habitica (using the email address I sent you privately) so I can take a look? Thanks!

**Comment by bumbleshoot** [comment]
Ok, @benniefolyfe if it happens again let me know so I can take a look! Closing this issue for now.

**Comment by bumbleshoot** [comment]
@KevinTyrrell5381 Does [this comment](https://github.com/bumbleshoot/automate-habitica/issues/10#issuecomment-1483732448) above solve your issue?

**Comment by KevinTyrrell5381** [comment]
@bumbleshoot I'm running a number of google apps scripts, so it must be the combination of them that is exceeding the 20,000/day limit. I'll take a look through to see which ones I can remove or trim back to be under the limit. Thanks.
