### ISSUE TITLE
Error: "You already have maximum health."

### ISSUE THREAD

**Issue by sundaresvani** [bumbleshoot/automate-habitica#12]
**What is the bug?**
received an error message -- yep, I'm at full health... why'd it try? 
---------- Forwarded message ---------- From: [svani.shop@gmail.com](mailto:svani.shop@gmail.com) Date: Mar 27, 2023, 08:05 -0700 To: [svani.shop@gmail.com](mailto:svani.shop@gmail.com) Subject: Automate Habitica failed!

Error: Request failed for https://habitica.com/ returned code 401. Truncated server response: {"success":false,"error":"NotAuthorized","message":"You already have maximum health."} at fetch (global:604:13) at healParty (automations/castHealerSkills:131:7) at processQueue (global:358:11) at onTrigger (global:27:5) at GS_INTERNAL_top_function_call.gs:1:8

**Additional context**
Umm it was just a normal day. 

**How often does this happen?**
it only happened once.

**Script version**
Umm  it was pretty up to date. I don't know & have deleted to get the latest version 

**Script settings**
```

const AUTO_CRON = false; // true or false

const AUTO_ACCEPT_QUEST_INVITES = true;

const FORCE_START_QUESTS = true; // party leaders only
const FORCE_START_QUESTS_AFTER_HOURS = 2; // eg. if set to 1, quests will force start after 1h
const NOTIFY_MEMBERS_EXCLUDED_FROM_QUEST = true;

const AUTO_INVITE_GOLD_QUESTS = false;
const AUTO_INVITE_UNLOCKABLE_QUESTS = false;
const AUTO_INVITE_PET_QUESTS = false;
const AUTO_INVITE_HOURGLASS_QUESTS = false;
const PM_WHEN_OUT_OF_QUEST_SCROLLS = true;

const NOTIFY_ON_QUEST_END = true;

const AUTO_CAST_SKILLS = true;

const AUTO_PAUSE_RESUME_DAMAGE = false;
const MAX_PLAYER_DAMAGE = 20;
const MAX_PARTY_DAMAGE = 5;

const AUTO_ALLOCATE_STAT_POINTS = true;
const STAT_TO_ALLOCATE = "int"; // str, int, con, per

const AUTO_PURCHASE_GEMS = false; // subscribers only

const AUTO_PURCHASE_ARMOIRES = true;
const RESERVE_GOLD = 300;

const AUTO_SELL_EGGS = false;
const RESERVE_EGGS = 999;

const AUTO_SELL_HATCHING_POTIONS = false;
const RESERVE_HATCHING_POTIONS = 999;

const AUTO_SELL_FOOD = false;
const RESERVE_FOOD = 999;

const AUTO_HATCH_FEED_PETS = true;
const ONLY_USE_DROP_FOOD = true;

const HIDE_PARTY_NOTIFICATIONS = true;
const HIDE_ALL_GUILD_NOTIFICATIONS = true;
const HIDE_NOTIFICATIONS_FROM_SPECIFIC_GUILDS = [ // only used if HIDE_ALL_GUILD_NOTIFICATIONS is false
  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", // enter a guild ID between the quotes to hide notifications from that guild
  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" // repeat for as many guilds as you want
]

```

**Comment by bumbleshoot** [comment]
Hi @sundaresvani, can you please go to [scripts.google.com](https://script.google.com/home), log in if necessary, click on “Trash” in the main menu on the left, find your old copy of Automate Habitica, and update your bug report with the script version? It is important for debugging! Thanks!

**Comment by bumbleshoot** [comment]
Hi again @sundaresvani, I think I have fixed the issue - please follow [these instructions](https://github.com/bumbleshoot/automate-habitica#updating-the-script) to update your script. If it happens again, please let me know here and provide the new error message and script version. Thanks!
