### ISSUE TITLE
Getting error "Task not found" in Automate Habitica v0.29.22

### ISSUE THREAD

**Issue by jabberwocky871** [bumbleshoot/automate-habitica#14]
**What is the bug?**
Receiving emails:
Automate Habitica v0.29.22 failed!

Error: Request failed for https://habitica.com returned code 404. Truncated
server response: {"success":false,"error":"NotFound","message":"Task not
found."}
at fetch (global:604:13)
at burnBossAndDumpMana (automations/castMageSkills:146:11)
at beforeCronSkills (global:493:5)
at processQueue (global:368:11)
at onTrigger (global:27:5)
at GS_INTERNAL_top_function_call.gs:1:8

**Additional context**
I upgraded the Automate Habitica to version v0.29.22 on April 2 and started receiving the error message shown above via email.
Note that I'm a party leader and have FORCE_START_QUESTS enabled.

**How often does this happen?**
The timestamps on the emails were approximately every 10 minutes. They stopped once I set auto_cast_skills to false.

**Script version**
v0.29.22 

**Script settings**
```
const AUTO_CRON = false; // true or false

const AUTO_ACCEPT_QUEST_INVITES = true;

const FORCE_START_QUESTS = true; // party leaders only
const FORCE_START_QUESTS_AFTER_HOURS = 1; // eg. if set to 1, quests will force start after 1h
const NOTIFY_MEMBERS_EXCLUDED_FROM_QUEST = true;

const AUTO_INVITE_GOLD_QUESTS = false;
const AUTO_INVITE_UNLOCKABLE_QUESTS = false;
const AUTO_INVITE_PET_QUESTS = true;
const AUTO_INVITE_HOURGLASS_QUESTS = true;
const PM_WHEN_OUT_OF_QUEST_SCROLLS = true;

const NOTIFY_ON_QUEST_END = true;

const AUTO_CAST_SKILLS = true;

const AUTO_PAUSE_RESUME_DAMAGE = false;
const MAX_PLAYER_DAMAGE = 20;
const MAX_PARTY_DAMAGE = 5;

const AUTO_ALLOCATE_STAT_POINTS = true;
const STAT_TO_ALLOCATE = "int"; // str, int, con, per

const AUTO_PURCHASE_GEMS = false; // subscribers only

const AUTO_PURCHASE_ARMOIRES = true;
const RESERVE_GOLD = 1000;

const AUTO_SELL_EGGS = false;
const RESERVE_EGGS = 999;

const AUTO_SELL_HATCHING_POTIONS = false;
const RESERVE_HATCHING_POTIONS = 999;

const AUTO_SELL_FOOD = false;
const RESERVE_FOOD = 999;

const AUTO_HATCH_FEED_PETS = false;
const ONLY_USE_DROP_FOOD = true;

const HIDE_PARTY_NOTIFICATIONS = false;
const HIDE_ALL_GUILD_NOTIFICATIONS = false;
const HIDE_NOTIFICATIONS_FROM_SPECIFIC_GUILDS = [ // only used if HIDE_ALL_GUILD_NOTIFICATIONS is false
  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", // enter a guild ID between the quotes to hide notifications from that guild
  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" // repeat for as many guilds as you want
]```

**Comment by jabberwocky871** [comment]
FYI, I run a few different users in Habitica and noticed that only the Mage and Warrior are getting this error, not the Healer or Rogue. Further evidence that this is related to the boss attacks from smash and fireball.

**Comment by bumbleshoot** [comment]
Hi @jabberwocky871, this is an interesting error. The script is trying to cast Burst of Flames on your bluest task, but when it finds the bluest task and attempts to cast Burst of Flames on it, the error "task not found" is thrown. The script won't try to cast Burst of Flames on a challenge or reward task, so I can't think of why this would happen.

I'd like to turn your Auto Cast Skills back on, then if you keep getting the error, I will add some code to your script to find out what task is causing the error. I'll reach out to you via DM to continue troubleshooting. :)

**Comment by bumbleshoot** [comment]
@jabberwocky871 Based on our troubleshooting, it seems skills cannot be cast on group tasks. I have updated Automate Habitica to ignore group tasks when it attempts to cast a skill on a task. Can you please [update your script](https://github.com/bumbleshoot/automate-habitica#updating-the-script) and let me know if that solves the problem?

**Comment by jabberwocky871** [comment]
So no error emails today. Looking good. Once thing that I don't see is any buffs being auto-cast in the party chat feed. Is there a way to see if Auto Cast Skills is being triggered?

**Comment by bumbleshoot** [comment]
@jabberwocky871 Yes, you can check your script's Execution Logs (go to your script and click on Execution Logs in the main menu on the left) to see whether buffs are being cast. Look at execution logs for the "onTrigger" function. Buffs will only be cast when you have excess mana (see [the documentation](https://github.com/bumbleshoot/automate-habitica#auto-cast-skills) for an explanation of what is meant by "excess mana").

The "Task not found" error seems to be resolved so I will close this issue!
