### ISSUE TITLE
"When a quest is finished or the user is invited to a quest" webhook disabled

### ISSUE THREAD

**Issue by Ayrenne** [bumbleshoot/automate-habitica#15]
**What is the bug?**
"When a quest is finished or the user is invited to a quest" webhook disabled repeatedly.

**Additional context**
None...

**How often does this happen?**
Once every few days, for the last 6 weeks or so.

**Script version**
Version: v0.29.20 (beta)

**Script settings**
```
const AUTO_CRON = false; // true or false

const AUTO_ACCEPT_QUEST_INVITES = true;

const FORCE_START_QUESTS = false; // party leaders only
const FORCE_START_QUESTS_AFTER_HOURS = 1; // eg. if set to 1, quests will force start after 1h
const NOTIFY_MEMBERS_EXCLUDED_FROM_QUEST = true;

const AUTO_INVITE_GOLD_QUESTS = false;
const AUTO_INVITE_UNLOCKABLE_QUESTS = false;
const AUTO_INVITE_PET_QUESTS = false;
const AUTO_INVITE_HOURGLASS_QUESTS = false;
const PM_WHEN_OUT_OF_QUEST_SCROLLS = true;

const NOTIFY_ON_QUEST_END = true;

const AUTO_CAST_SKILLS = true;

const AUTO_PAUSE_RESUME_DAMAGE = true;
const MAX_PLAYER_DAMAGE = 20;
const MAX_PARTY_DAMAGE = 5;

const AUTO_ALLOCATE_STAT_POINTS = false;
const STAT_TO_ALLOCATE = "int"; // str, int, con, per

const AUTO_PURCHASE_GEMS = true; // subscribers only

const AUTO_PURCHASE_ARMOIRES = false;
const RESERVE_GOLD = 50000;

const AUTO_SELL_EGGS = false;
const RESERVE_EGGS = 999;

const AUTO_SELL_HATCHING_POTIONS = false;
const RESERVE_HATCHING_POTIONS = 999;

const AUTO_SELL_FOOD = false;
const RESERVE_FOOD = 999;

const AUTO_HATCH_FEED_PETS = true;
const ONLY_USE_DROP_FOOD = true;

const HIDE_PARTY_NOTIFICATIONS = false;
const HIDE_ALL_GUILD_NOTIFICATIONS = false;
const HIDE_NOTIFICATIONS_FROM_SPECIFIC_GUILDS = [ // only used if HIDE_ALL_GUILD_NOTIFICATIONS is false
  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", // enter a guild ID between the quotes to hide notifications from that guild
  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" // repeat for as many guilds as you want
```

**Comment by bumbleshoot** [comment]
Hey @Ayrenne, as far as I know, Habitca's webhooks can be disabled for 2 reasons: 1) the script throws an error (which would cause you to receive an email about the error), or 2) the script takes longer than 30 seconds to run when the webhook calls it. In both cases, this has to happen 5 times in a month for the webhook to be disabled (if I am remembering correctly). Have you been receiving any error messages from Automate Habitica in your email?

**Comment by Ayrenne** [comment]
I had 5 error message emails in March, 4 of which were 502 errors. None in April. Not enough to justify the webhook being disabled.

**Comment by bumbleshoot** [comment]
Hi @Ayrenne, thanks so much for your patience with this! I have implemented a temporary fix while we wait for Google to fix [this issue](https://issuetracker.google.com/issues/231411987) with Google Apps Script. If you [update your script](https://github.com/bumbleshoot/automate-habitica#updating-the-script), you should not encounter this issue anymore! 🤞
