### ISSUE TITLE
Improvement: Implement `STAT_TO_ALLOCATE = "auto"`

### ISSUE THREAD

**Issue by ramotar** [bumbleshoot/automate-habitica#21]
**What is the suggestion?**
Provide an automatic selection mode for `STAT_TO_ALLOCATE`, that allocates stat points depending on the current class of the user.

**Additional context**
Every class has a different main stat, that its skills are based on. When changing classes, one must remember to change the configuration of Automate Habitica. It would be quite easy to implement an automatic mode, that simply allocates the main stat for the current class of the user.

**Script settings**
The settings could then look like this:
```javascript
const STAT_TO_ALLOCATE = "auto"; // str, int, con, per, auto
```

**Comment by ramotar** [comment]
I would be happy to contribute this mode to Automate Habitica :)

**Comment by bumbleshoot** [comment]
Hi @ramotar, can you please submit this as a [suggestion](https://github.com/bumbleshoot/automate-habitica/discussions/categories/suggestions) rather than a bug report? Thanks!
