### ISSUE TITLE
trouble with cron

### ISSUE THREAD

**Issue by quomodoo** [bumbleshoot/automate-habitica#28]
**What is the bug?**
I'm unable to cron. Everything else seem fine, The script casts skills. 

**Additional context**
Yesterday, I received the following email. But after that things seems okay and the script was able to cast skills. Today, the character didn't cron when I open the app (and then browser). My cron time is +2. In tool.habitica it seems I completed some of dailies Thursday (yesterday) and some them on Friday (my late dailies are marked on friday). I marked some of my dailies around 1 am. More explicitly, let's say the I have dailies A,B,C. The daily A seems completed on Thursday while daily B (the one I clicked around 1 am) seems completed on Friday. And the daily A on Friday seems like gray (-). But in Habitica I can only see the daily C which I didn't complete and it didn't damage me. And my Friday-specific dailies didn't appear. 

Error: Request failed for https://habitica.com/ returned code 502. Truncated 
server response:
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your 
request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

     at fetch (global:638:13)
     at castEarthquake (automations/castMageSkills:55:7)
     at afterCronSkills (global:526:7)
     at processQueue (global:374:11)
     at onTrigger (global:27:5)
     at __GS_INTERNAL_top_function_call__.gs:1:8

**How often does this happen?** 
Only once

**Script version**/**
 * Automate Habitica v0.29.35 (beta) by @bumbleshoot
 *
 * See GitHub page for info & setup instructions:
 * https://github.com/bumbleshoot/automate-habitica
 */

**Script settings**
```
const AUTO_CRON = false; // true or false

const AUTO_ACCEPT_QUEST_INVITES = true;

const FORCE_START_QUESTS = false; // party leaders only
const FORCE_START_QUESTS_AFTER_HOURS = 1; // eg. if set to 1, quests will force start after 1h
const NOTIFY_MEMBERS_EXCLUDED_FROM_QUEST = true;

const AUTO_INVITE_GOLD_QUESTS = false;
const AUTO_INVITE_UNLOCKABLE_QUESTS = false;
const AUTO_INVITE_PET_QUESTS = false;
const AUTO_INVITE_HOURGLASS_QUESTS = false;
const PM_WHEN_OUT_OF_QUEST_SCROLLS = true;

const NOTIFY_ON_QUEST_END = true;

const AUTO_CAST_SKILLS = true;

const AUTO_PAUSE_RESUME_DAMAGE = true;
const MAX_PLAYER_DAMAGE = 20;
const MAX_PARTY_DAMAGE = 5;

const AUTO_ALLOCATE_STAT_POINTS = false;
const STAT_TO_ALLOCATE = "int"; // str, int, con, per

const AUTO_PURCHASE_GEMS = false; // subscribers only

const AUTO_PURCHASE_ARMOIRES = false;
const RESERVE_GOLD = 50000;

const AUTO_SELL_EGGS = false;
const RESERVE_EGGS = 999;

const AUTO_SELL_HATCHING_POTIONS = false;
const RESERVE_HATCHING_POTIONS = 999;

const AUTO_SELL_FOOD = false;
const RESERVE_FOOD = 999;

const AUTO_HATCH_FEED_PETS = false;
const ONLY_USE_DROP_FOOD = true;

const HIDE_PARTY_NOTIFICATIONS = false;
const HIDE_ALL_GUILD_NOTIFICATIONS = false;
const HIDE_NOTIFICATIONS_FROM_SPECIFIC_GUILDS = [ // only used if HIDE_ALL_GUILD_NOTIFICATIONS is false
  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", // enter a guild ID between the quotes to hide notifications from that guild
  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" // repeat for as many guilds as you want
]
```

**Comment by bumbleshoot** [comment]
Hi @quomodoo, I doubt this 502 error has anything to do with your cron problem (because it didn't happen at your cron time), and besides, 502 error means something went wrong on Habitica's servers (not something I can fix or look into unfortunately).

As far as I know, Habitica does not have an API endpoint that prevents cron (and if it does, Automate Habitica doesn't use it), so it is not possible for Automate Habitica to prevent you from cronning. I'm afraid you'll have to submit a bug report to the Habitica admins. :)
