### ISSUE TITLE
Force start quests error

### ISSUE THREAD

**Issue by blackcatsnow** [bumbleshoot/automate-habitica#5]
When attempting to install the force start quests causes errors. I'm not sure how to fix it. I have attached a copy of my google script without user or API but everything else is the same. https://script.google.com/d/136mmSijqvy5yYr9rZKf_uoYZDSeSzkCM5RRooFVqsJZziTPekP-59W2b/edit?usp=sharing

	
TypeError: Cannot read property 'quests' of undefined
forceStartQuest	@ automations/forceStartQuest.gs:79
processQueue	@ global.gs:319
install	@ setup.gs:83

**Comment by bumbleshoot** [comment]
Hi @blackcatsnow, thanks for bringing this to my attention! It has been fixed. Please [update to the latest version](https://github.com/bumbleshoot/automate-habitica#updating-the-script).
