### ISSUE TITLE
Auto Cast Skills documentation unclear

### ISSUE THREAD

**Issue by blackcatsnow** [bumbleshoot/automate-habitica#7]
I'm not sure if this is user error or a bug, but I've noticed that the script doesn't seem to leave 45 mana to cast stealth, it still casts tools of the trade perfectly though.

**Comment by bumbleshoot** [comment]
Hi @blackcatsnow, are you referring to #5 in [this list](https://github.com/bumbleshoot/automate-habitica#auto-cast-skills) - "Reserves enough mana to start each day with as much mana as possible, then uses all your mana to buff your class's primary stat just after cron"?

**Comment by blackcatsnow** [comment]
Yes! I may have misunderstood. I'm sorry. I seem to remember that it would reserve so mana to cast stealth but I may be wrong.

**Comment by bumbleshoot** [comment]
@blackcatsnow Mana is not reserved for Stealth, but Stealth is cast just before the rogue's day start time as needed, if there is enough mana. Does that make sense? Let me know if you think there is a better way to auto cast skills, or a better way to explain how it works in [the documentation](https://github.com/bumbleshoot/automate-habitica#auto-cast-skills)! :)

**Comment by bumbleshoot** [comment]
Well, #6 says "reserves mana for the items listed above", but #5 says "Reserves enough mana to start each day with as much mana as possible, then uses all your mana to buff your class's primary stat just after cron". So I can see why you might be confused, they technically contradict each other. All mana is spent on buffing the primary stat after cron, this is the only exception to "reserves mana for the items listed above". I'm not sure how to explain this better, but I'll think on it, and if you have any ideas for better wording, please do let me know!

Sorry for closing & reopening the issue, I clicked on the wrong button by accident and there's no way to undo it lol

**Comment by bumbleshoot** [comment]
@blackcatsnow Well, #6 says "reserves mana for the items listed above", but #5 says "Reserves enough mana to start each day with as much mana as possible, then uses all your mana to buff your class's primary stat just after cron". So I can see why you might be confused, they technically contradict each other. All mana is spent on buffing the primary stat after cron, this is the only exception to "reserves mana for the items listed above". I'm not sure how to explain this better, but I'll think on it, and if you have any ideas for better wording, please do let me know!

Sorry for closing & reopening the issue, I clicked on the wrong button by accident and there's no way to undo it lol

**Comment by bumbleshoot** [comment]
I improved the Auto Cast Skills documentation as much as I could. I couldn't think of a better way to explain the mana drain that happens after cron, though. If anyone has any suggestions, please let me know here and I'll reopen this issue. :)
