### ISSUE TITLE
Failure to Execute "install" Step

### ISSUE THREAD

**Issue by y2krazy** [bumbleshoot/automate-habitica#8]
**Failure to Execute "install" step.**
Cannot run "install" from the drop-down next to Debug.

**Steps to reproduce**
Follow the setup instructions.

**Expected behavior**
Return a "Execution completed" result.

**Screenshots**
![chrome_2023-01-28_01-23-18](https://user-images.githubusercontent.com/12468950/215252995-5d755c8a-3c9e-4d04-8287-97069bc940f4.png)

**Comment by y2krazy** [comment]
Strange. I just woke up and clicked Run again and there was no error this time and it went through to "Execution completed."

**Comment by bumbleshoot** [comment]
Hi @y2krazy, what quest was your party doing at the time?

**Comment by bumbleshoot** [comment]
Hi again @y2krazy, I'm quite certain I have fixed this issue now. Thanks for bringing it to my attention! Can you please [update your script](https://github.com/bumbleshoot/automate-habitica#updating-the-script)?
